# Generated by Django 6.0.5 on 2026-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_portal_againApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostmodel",
            name="skill_set",
            field=models.ManyToManyField(
                blank=True, to="job_portal_againApp.skillmodel"
            ),
        ),
        migrations.AlterField(
            model_name="jobseekerprofilemodel",
            name="skill_set",
            field=models.ManyToManyField(
                blank=True, to="job_portal_againApp.skillmodel"
            ),
        ),
        migrations.AlterField(
            model_name="skillmodel",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
