# Generated by Django 6.0.5 on 2026-05-12 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_portal_againApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
