# Generated by Django 6.0.5 on 2026-05-12 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_portal_againApp", "0002_alter_skillmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillmodel",
            name="user",
        ),
    ]
